# LigthGBM

In [165]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import lightgbm
import optuna
import shap
from sklearn.model_selection import KFold

## DataFrame Additional Methods

In [18]:
def out_df(self, head_or_tail: str ='head', n_display: int =1) -> None:
    h_or_t = {'head': self.head(n_display),
              'tail': self.tail(n_display)}
    print(self.shape)
    display(h_or_t[head_or_tail])
    
pd.DataFrame.out_df = out_df

## Constant

In [88]:
APPLY_KFOLD = {'n_splits': 3,
               'shuffle': True,
               'random_state': 0}

## Class

In [110]:
class MyKFold:
    def __init__(self, 
                 df: pd.DataFrame, 
                 id_key: list =None,
                 n_split: int =1):
        self.df = df
        self.id_key = id_key
        self.n_split = n_split
    
    def add_id(self):
        if self.id_key is not None:
            return self.df
        
        df_add_id = self.df.copy()
        id_list = [i + 1 for i in range(len(self.df))]
        df_add_id.insert(0, 'id', id_list)
        return df_add_id
    
    def add_kfold(self):
        df_add_id = self.add_id()
        
        
        
        pass

In [104]:
class MyLightGBM:
    def __init__(self, 
                 df: pd.DataFrame,
                 col_X: list,
                 col_y: str) -> None:
        self.df = df
        self.col_X = col_X
        self.col_y = col_y
    
    def tuning_by_optuna(self, hyper_params) -> dict:
        """
        Decision hyper parameter on hyper_params as best test accuracy.
        """    
        pass
        
    def evaluate_by_kfold(self) -> dict:
        """
        Evaluate train and test accuracy by fold ID.
        """
        pass
    
    def feature_importance(self) -> pd.DataFrame:
        """
        Output feature importance DataFrame.
        """
        pass
    
    def shap_by_feature_importance(self) -> None:
        """
        Output summary plot of SHAP of feature importance.
        """
        pass

## Datasets

In [51]:
df_iris = pd.read_csv('../../data/iris.csv').reset_index(drop=True)
df_iris.out_df()

(150, 5)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [171]:
np.random.seed(0)

TypeError: 'int' object is not callable

In [121]:
mykfold = MyKFold(df_iris, id_key=None, n_split=3)
df_iris_add_id = mykfold.add_id('id')
df_iris_add_id.out_df()

(150, 6)


id  sepal_length  sepal_width  petal_length  petal_width species
0   1           5.1          3.5           1.4          0.2  setosa

In [55]:
col_iris_X = df_iris.columns.tolist()[0:4]
col_iris_y = df_iris.columns.tolist()[4]
col_iris_X, col_iris_y

(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], 'species')

In [87]:
na_iris_X = df_iris[col_iris_X].values
na_iris_y = df_iris[col_iris_y].values

## Apply KFold

In [ ]:
def apply_kfold(df: pd.DataFrame) -> pd.DataFrame:
    

TypeError: 'int' object is not callable

In [160]:
np.random.seed(0)

TypeError: 'int' object is not callable

In [158]:
np.random.seed
np.random.randint(1,3+1,20) 

array([2, 2, 3, 2, 3, 2, 2, 2, 2, 3, 1, 2, 2, 3, 2, 1, 3, 2, 1, 3])

TypeError: 'int' object is not callable

In [122]:
kf = KFold(APPLY_KFOLD['n_splits'], APPLY_KFOLD['shuffle'], APPLY_KFOLD['random_state'])
df_iris_add_id['fold_id'] = 0
for fold_id, id_key in enumerate(kf.split(na_iris_X)):
    df_iris_add_id.loc[df_iris_add_id['id'].isin(id_key[1]), 'fold_id'] = fold_id + 1
df_iris_add_id

id  sepal_length  sepal_width  petal_length  petal_width    species  \
0      1           5.1          3.5           1.4          0.2     setosa   
1      2           4.9          3.0           1.4          0.2     setosa   
2      3           4.7          3.2           1.3          0.2     setosa   
3      4           4.6          3.1           1.5          0.2     setosa   
4      5           5.0          3.6           1.4          0.2     setosa   
5      6           5.4          3.9           1.7          0.4     setosa   
6      7           4.6          3.4           1.4          0.3     setosa   
7      8           5.0          3.4           1.5          0.2     setosa   
8      9           4.4          2.9           1.4          0.2     setosa   
9     10           4.9          3.1           1.5          0.1     setosa   
10    11           5.4          3.7           1.5          0.2     setosa   
11    12           4.8          3.4           1.6          0.2     setosa   
12    13           4.8          3.0           1.4          0.1     setosa   
13    14           4.3          3.0           1.1          0.1     setosa   
14    15           5.8          4.0           1.2          0.2     setosa   
15    16           5.7          4.4           1.5          0.4     setosa   
16    17           5.4          3.9           1.3          0.4     setosa   
17    18           5.1          3.5           1.4          0.3     setosa   
18    19           5.7          3.8           1.7          0.3     setosa   
19    20           5.1          3.8           1.5          0.3     setosa   
20    21           5.4          3.4           1.7          0.2     setosa   
21    22           5.1          3.7           1.5          0.4     setosa   
22    23           4.6          3.6           1.0          0.2     setosa   
23    24           5.1          3.3           1.7          0.5     setosa   
24    25           4.8          3.4           1.9          0.2     setosa   
25    26           5.0          3.0           1.6          0.2     setosa   
26    27           5.0          3.4           1.6          0.4     setosa   
27    28           5.2          3.5           1.5          0.2     setosa   
28    29           5.2          3.4           1.4          0.2     setosa   
29    30           4.7          3.2           1.6          0.2     setosa   
..   ...           ...          ...           ...          ...        ...   
120  121           6.9          3.2           5.7          2.3  virginica   
121  122           5.6          2.8           4.9          2.0  virginica   
122  123           7.7          2.8           6.7          2.0  virginica   
123  124           6.3          2.7           4.9          1.8  virginica   
124  125           6.7          3.3           5.7          2.1  virginica   
125  126           7.2          3.2           6.0          1.8  virginica   
126  127           6.2          2.8           4.8          1.8  virginica   
127  128           6.1          3.0           4.9          1.8  virginica   
128  129           6.4          2.8           5.6          2.1  virginica   
129  130           7.2          3.0           5.8          1.6  virginica   
130  131           7.4          2.8           6.1          1.9  virginica   
131  132           7.9          3.8           6.4          2.0  virginica   
132  133           6.4          2.8           5.6          2.2  virginica   
133  134           6.3          2.8           5.1          1.5  virginica   
134  135           6.1          2.6           5.6          1.4  virginica   
135  136           7.7          3.0           6.1          2.3  virginica   
136  137           6.3          3.4           5.6          2.4  virginica   
137  138           6.4          3.1           5.5          1.8  virginica   
138  139           6.0          3.0           4.8          1.8  virginica   
139  140           6.9          3.1           5.4          2.1  virginica   
14

In [89]:
kf = KFold(APPLY_KFOLD['n_splits'], APPLY_KFOLD['shuffle'], APPLY_KFOLD['random_state'])
for trn_idx, tst_idx in kf.split(na_iris_X):
    display(trn_idx)
#     X_trn, X_tst = na_iris_X[trn_idx], na_iris_X[tst_idx]
#     y_trn, y_tst = na_iris_y[trn_idx], na_iris_y[tst_idx]

array([  0,   1,   3,   4,   5,   6,   9,  11,  12,  13,  14,  15,  17,
        19,  20,  21,  23,  25,  28,  29,  30,  31,  32,  34,  35,  36,
        38,  39,  41,  42,  46,  47,  48,  49,  50,  52,  53,  55,  56,
        57,  58,  64,  65,  67,  68,  69,  70,  72,  74,  75,  77,  79,
        80,  81,  82,  85,  87,  88,  89,  91,  94,  95,  96,  98,  99,
       101, 102, 103, 104, 105, 106, 109, 110, 111, 113, 115, 117, 118,
       120, 122, 123, 124, 125, 128, 129, 130, 131, 133, 135, 136, 138,
       139, 140, 142, 143, 145, 146, 147, 148, 149])

array([  0,   2,   5,   7,   8,   9,  10,  14,  16,  18,  19,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  43,  44,  45,  47,  49,  51,  53,  54,  55,
        57,  58,  59,  60,  61,  62,  63,  65,  66,  67,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  81,  82,  83,  84,  86,  87,
        88,  90,  92,  93,  97,  99, 100, 103, 105, 107, 108, 112, 114,
       115, 116, 117, 118, 119, 121, 122, 126, 127, 130, 131, 132, 134,
       136, 137, 138, 140, 141, 142, 143, 144, 145])

array([  1,   2,   3,   4,   6,   7,   8,  10,  11,  12,  13,  15,  16,
        17,  18,  20,  22,  24,  26,  27,  30,  33,  37,  40,  41,  42,
        43,  44,  45,  46,  48,  50,  51,  52,  54,  56,  59,  60,  61,
        62,  63,  64,  66,  68,  69,  71,  73,  76,  78,  80,  83,  84,
        85,  86,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98, 100,
       101, 102, 104, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116,
       119, 120, 121, 123, 124, 125, 126, 127, 128, 129, 132, 133, 134,
       135, 137, 139, 141, 144, 146, 147, 148, 149])

## Tuning by Optuna

1

## Validation

## Shap Analysis